---
apiVersion: apps/v1    
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress-database
spec:
  selector:
    matchLabels:
      app: wordpress-database
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wordpress-database
    spec:
      containers:
        - image: mysql:latest
          name: mysql
          env:
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-auth
                  key: pass
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
