---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
  labels:
    type: pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/wordpress/pv-1
  persistentVolumeReclaimPolicy: Delete

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-2
  labels:
    type: pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/wordpress/pv-2
  persistentVolumeReclaimPolicy: Delete
