---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  externalIPs:
  - 192.168.0.31
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: wordpress
